image: node

stages:
  - lint

eslint:
  stage: lint
  script:
    - |
      npm install eslint \
      eslint-config-airbnb \
      eslint-config-prettier \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y \
      eslint-plugin-prettier \
      eslint-plugin-react \
      @typescript-eslint/eslint-plugin \
      @typescript-eslint/parser
    - node_modules/eslint/bin/eslint.js .
